name: escoge
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  firebase_core: ^3.13.0
  cloud_firestore: ^5.6.6
  google_sign_in: ^7.0.0
  firebase_auth: ^5.5.2
  intl: ^0.19.0
  file_picker: ^8.1.2
  shared_preferences: ^2.2.3
  audioplayers: ^6.1.0
  flutter_svg: ^2.0.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/rosario/Gozosos/
    - assets/images/rosario/Dolorosos/
    - assets/images/rosario/Gloriosos/
    - assets/images/rosario/Luminosos/
    - assets/logos/logo.png
    - assets/backgrounds/
    - assets/backgrounds/form.png
    - assets/seeds/liturgia_import.json
    - assets/audio/gozosos/
    - assets/audio/dolorosos/
    - assets/audio/gloriosos/
    - assets/audio/luminosos/
    - assets/icons/
    