// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMYW_ELW6MxtHe_Li5AumbPbowVjadogU',
    appId: '1:825946489840:android:ac49a33bce3f8aa4e11335',
    messagingSenderId: '825946489840',
    projectId: 'escoge-f36dc',
    storageBucket: 'escoge-f36dc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDt5RHPyllSneezD796bYl9mWxjl8-L8Ns',
    appId: '1:825946489840:ios:d55c43a9a09cee3ce11335',
    messagingSenderId: '825946489840',
    projectId: 'escoge-f36dc',
    storageBucket: 'escoge-f36dc.firebasestorage.app',
    iosBundleId: 'com.example.escoge',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCg4XddRQc70bENXQ9D8Jk-auE66LHytu4',
    appId: '1:825946489840:web:8eb5bf484172495fe11335',
    messagingSenderId: '825946489840',
    projectId: 'escoge-f36dc',
    authDomain: 'escoge-f36dc.firebaseapp.com',
    storageBucket: 'escoge-f36dc.firebasestorage.app',
    measurementId: 'G-JKP6R77TR2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDt5RHPyllSneezD796bYl9mWxjl8-L8Ns',
    appId: '1:825946489840:ios:d55c43a9a09cee3ce11335',
    messagingSenderId: '825946489840',
    projectId: 'escoge-f36dc',
    storageBucket: 'escoge-f36dc.firebasestorage.app',
    iosBundleId: 'com.example.escoge',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCg4XddRQc70bENXQ9D8Jk-auE66LHytu4',
    appId: '1:825946489840:web:09f5c46ac62f2db5e11335',
    messagingSenderId: '825946489840',
    projectId: 'escoge-f36dc',
    authDomain: 'escoge-f36dc.firebaseapp.com',
    storageBucket: 'escoge-f36dc.firebasestorage.app',
    measurementId: 'G-QC42YHSVC9',
  );

}