// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBh4necMeotmXIa_fX4eP2VNKcAwnMtXj0',
    appId: '1:735501422337:web:6b9007152c8a557ae99500',
    messagingSenderId: '735501422337',
    projectId: 'escogerd-48354',
    authDomain: 'escogerd-48354.firebaseapp.com',
    storageBucket: 'escogerd-48354.firebasestorage.app',
    measurementId: 'G-788YH35WYF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7KwOLfGI1FYQnTvj3FBwiPDSzajz3HIM',
    appId: '1:735501422337:android:4b161c7b0a88d118e99500',
    messagingSenderId: '735501422337',
    projectId: 'escogerd-48354',
    storageBucket: 'escogerd-48354.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCUZ-KzZEXz30zjm9wKluhErliOFvOYe8',
    appId: '1:735501422337:ios:87e9cbd847adf908e99500',
    messagingSenderId: '735501422337',
    projectId: 'escogerd-48354',
    storageBucket: 'escogerd-48354.firebasestorage.app',
    iosBundleId: 'com.example.escoge',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCUZ-KzZEXz30zjm9wKluhErliOFvOYe8',
    appId: '1:735501422337:ios:87e9cbd847adf908e99500',
    messagingSenderId: '735501422337',
    projectId: 'escogerd-48354',
    storageBucket: 'escogerd-48354.firebasestorage.app',
    iosBundleId: 'com.example.escoge',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBh4necMeotmXIa_fX4eP2VNKcAwnMtXj0',
    appId: '1:735501422337:web:0fe0931b3c5d929ee99500',
    messagingSenderId: '735501422337',
    projectId: 'escogerd-48354',
    authDomain: 'escogerd-48354.firebaseapp.com',
    storageBucket: 'escogerd-48354.firebasestorage.app',
    measurementId: 'G-4KCHWW3L9X',
  );
}
